---
# tasks file for roles/nginx
- name: Remove Apache and its configuration
  apt:
    name:
      - apache2
      - apache2-utils
    state: absent
    purge: yes

- name: Remove Nginx and its configuration
  apt:
    name:
      - nginx
      - nginx-common
    state: absent
    purge: yes

- name: Remove Apache configuration directory
  file:
    path: /etc/apache2
    state: absent

- name: Remove Nginx configuration directory
  file:
    path: /etc/nginx
    state: absent

- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

 # Открытие порта 80 для HTTP (если используется брандмауэр UFW)
- name: Allow HTTP port 80 through firewall (UFW)
  ufw:
    rule: allow
    name: 'Nginx HTTP'

# Открытие порта 443 для HTTPS (если используется брандмауэр UFW)
- name: Allow HTTPS port 443 through firewall (UFW)
  ufw:
    rule: allow
    name: 'Nginx HTTPS'

- name: Configure Nginx to listen on external IP
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80;
          listen [::]:80;

          server_name 45.9.0.117;

          root /var/www/html;
          index index.html index.htm;

          location / {
              try_files $uri $uri/ =404;
          }
      }
  notify:
    - restart nginx

#
#- name: Update Nginx configuration to use port 8083
#  replace:
#    path: /etc/nginx/sites-available/default
#    regexp: 'listen \d+'
#    replace: 'listen 8083'
#  become: yes
