---
# Задачи, запускаемые для nginx

# Удаление Apache
- name: Remove Apache and its configuration
  apt:
    name:
      - apache2
      - apache2-utils
    state: absent
    purge: yes

# Удаление Nginx
- name: Remove Nginx and its configuration
  apt:
    name:
      - nginx
      - nginx-common
    state: absent
    purge: yes

# Удаление файлов конфигурации Apache
- name: Remove Apache configuration directory
  file:
    path: /etc/apache2
    state: absent

# Удаление файлов конфигурации Nginx
- name: Remove Nginx configuration directory
  file:
    path: /etc/nginx
    state: absent

# Установка Nginx
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

# Открытие порта 80 для HTTP
- name: Configure Nginx to listen on external IP
  copy:
    dest: /etc/nginx/sites-available/default
    content: |
      server {
          listen 80;
          listen [::]:80;

          server_name 45.9.40.117;

          root /var/www/html;
          index index.html index.htm index.nginx-debian.html;

          location / {
              try_files $uri $uri/ =404;
          }
      }

  # Хэндлера для перезапуска Nginx
  notify:
    - restart nginx
